es_name: "Sep_CMA_ES"
problem_type: "mnist"
normalize: false
es_config:
  pop_size: 100
  elite_ratio: 0.5
  init_stdev: 0.065
hidden_size: 100
batch_size: 1024
max_iter: 2000
test_interval: 500
log_interval: 100
num_tests: 1
n_repeats: 1
seed: 42
gpu_id: [0, 1, 2, 3]
debug: false
