es_name: "ARS_native"
problem_type: "waterworld_ma"
normalize: false
es_config:
  elite_ratio: 0.5
  pop_size: 16
  init_stdev: 0.1
  decay_stdev: 0.999
  limit_stdev: 0.001
  optimizer: "sgd"
  optimizer_config: 
    lrate_init: 0.01
    lrate_limit: 0.01
    decay_coef: 1
hidden_size: 100
num_tests: 16
n_repeats: 64
max_iter: 2000
test_interval: 100
log_interval: 10
seed: 42
gpu_id: 0
debug: false
