es_name: "PGPE"
problem_type: "cartpole_easy"
normalize: false
es_config:
  pop_size: 64
  center_learning_rate: 0.05
  stdev_learning_rate: 0.1
  init_stdev: 0.1
  optimizer: "adam"
hidden_size: 64
num_tests: 100
n_repeats: 16
max_iter: 1000
test_interval: 100
log_interval: 20
seed: 42
gpu_id: [0, 1, 2, 3]
debug: false