es_name: "CMA_ES_JAX"
problem_type: "cartpole_hard"
normalize: false
es_config:
  pop_size: 128
hidden_size: 64
num_tests: 100
n_repeats: 16
max_iter: 1000
test_interval: 100
log_interval: 20
seed: 42
gpu_id: 1
debug: false