es_name: "CMA_ES_JAX"
problem_type: "mnist"
normalize: false
es_config:
  pop_size: 128
hidden_size: 100
batch_size: 1024
max_iter: 2000
test_interval: 100
log_interval: 10
num_tests: 1
n_repeats: 1
seed: 42
gpu_id: [3]
debug: false
