es_name: "CRFMNES"
problem_type: "cartpole_easy"
normalize: false
es_config:
  pop_size: 64
  init_stdev: 0.3
hidden_size: 64
num_tests: 100
n_repeats: 16
max_iter: 1000
test_interval: 100
log_interval: 50
seed: 42
gpu_id: 0
debug: false
